# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::DefaultComponent`.

class Boxchat::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
