# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::SampleComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::SampleComponent`.

class Boxchat::SampleComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
