# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Badge::BorderComponent`.
# Please instead update this file by running `bin/tapioca dsl Badge::BorderComponent`.

class Badge::BorderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
