# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Badge::PillComponent`.
# Please instead update this file by running `bin/tapioca dsl Badge::PillComponent`.

class Badge::PillComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
