import Education_EducationOwner_EducationStudents_ImportViewController from "controllers/education/education_owner/education_students/import_view_controller";


export default class Education_EducationAdmin_EducationStudents_ImportViewController extends Education_EducationOwner_EducationStudents_ImportViewController {
  

}