version: '3.2'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # This constraint ensures the PostgreSQL service is deployed to a manager node
        # as it is a single-replica service and requires stable storage.
        constraints:
          - node.role == manager

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  mongo_data: