version: '3.2'

services:
  postgres:
    image: postgres:15
    environment:
      # These environment variables configure the PostgreSQL database.
      # It is highly recommended to use Docker secrets or environment variables for production passwords.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      # This volume ensures your data persists even if the container is removed or replaced.
      - postgres_data:/var/lib/postgresql/data
    ports:
      # This exposes the standard PostgreSQL port (5432) to the host machine.
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # This constraint ensures the PostgreSQL service is deployed to a manager node
        # as it is a single-replica service and requires stable storage.
        constraints:
          - node.role == manager

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  postgres_data: