name: skyceer_development
services:
  skyceer_web:
    image: pkphung2001/skyceer_rails:latest
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    volumes:
      - skyceer_web_data:/rails
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker

  job:
    image: pkphung2001/skyceer_rails:latest
    command: bin/jobs
    volumes:
      - skyceer_job_data:/rails
    depends_on:
      - skyceer_web
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker

volumes:
  skyceer_web_data:
  skyceer_job_data:
