# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::CopyContextBeforeComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::CopyContextBeforeComponent`.

class Button::CopyContextBeforeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
