# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::CopyLinkComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::CopyLinkComponent`.

class Button::CopyLinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
