# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::ReadMoreComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::ReadMoreComponent`.

class Button::ReadMoreComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
