# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::UpToTopComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::UpToTopComponent`.

class Button::UpToTopComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
