# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Chart::ApexComponent`.
# Please instead update this file by running `bin/tapioca dsl Chart::ApexComponent`.

class Chart::ApexComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
