# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BoxComponent`.
# Please instead update this file by running `bin/tapioca dsl BoxComponent`.

class BoxComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
