# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImgComponent`.
# Please instead update this file by running `bin/tapioca dsl ImgComponent`.

class ImgComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
