# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InputComponent`.
# Please instead update this file by running `bin/tapioca dsl InputComponent`.

class InputComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
