# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ListComponent`.
# Please instead update this file by running `bin/tapioca dsl ListComponent`.

class ListComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
