# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ModalComponent`.
# Please instead update this file by running `bin/tapioca dsl ModalComponent`.

class ModalComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
