# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SwitchComponent`.
# Please instead update this file by running `bin/tapioca dsl SwitchComponent`.

class SwitchComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
