# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TabComponent`.
# Please instead update this file by running `bin/tapioca dsl TabComponent`.

class TabComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
