# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TextComponent`.
# Please instead update this file by running `bin/tapioca dsl TextComponent`.

class TextComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
