# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AccordionComponent`.
# Please instead update this file by running `bin/tapioca dsl AccordionComponent`.

class AccordionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
