require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/agriculture_merchants", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AgricultureMerchant. As you add validations to AgricultureMerchant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AgricultureMerchant.create! valid_attributes
      get agriculture_merchants_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      agriculture_merchant = AgricultureMerchant.create! valid_attributes
      get agriculture_merchant_url(agriculture_merchant)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_agriculture_merchant_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      agriculture_merchant = AgricultureMerchant.create! valid_attributes
      get edit_agriculture_merchant_url(agriculture_merchant)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AgricultureMerchant" do
        expect {
          post agriculture_merchants_url, params: { agriculture_merchant: valid_attributes }
        }.to change(AgricultureMerchant, :count).by(1)
      end

      it "redirects to the created agriculture_merchant" do
        post agriculture_merchants_url, params: { agriculture_merchant: valid_attributes }
        expect(response).to redirect_to(agriculture_merchant_url(AgricultureMerchant.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AgricultureMerchant" do
        expect {
          post agriculture_merchants_url, params: { agriculture_merchant: invalid_attributes }
        }.to change(AgricultureMerchant, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post agriculture_merchants_url, params: { agriculture_merchant: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested agriculture_merchant" do
        agriculture_merchant = AgricultureMerchant.create! valid_attributes
        patch agriculture_merchant_url(agriculture_merchant), params: { agriculture_merchant: new_attributes }
        agriculture_merchant.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the agriculture_merchant" do
        agriculture_merchant = AgricultureMerchant.create! valid_attributes
        patch agriculture_merchant_url(agriculture_merchant), params: { agriculture_merchant: new_attributes }
        agriculture_merchant.reload
        expect(response).to redirect_to(agriculture_merchant_url(agriculture_merchant))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        agriculture_merchant = AgricultureMerchant.create! valid_attributes
        patch agriculture_merchant_url(agriculture_merchant), params: { agriculture_merchant: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agriculture_merchant" do
      agriculture_merchant = AgricultureMerchant.create! valid_attributes
      expect {
        delete agriculture_merchant_url(agriculture_merchant)
      }.to change(AgricultureMerchant, :count).by(-1)
    end

    it "redirects to the agriculture_merchants list" do
      agriculture_merchant = AgricultureMerchant.create! valid_attributes
      delete agriculture_merchant_url(agriculture_merchant)
      expect(response).to redirect_to(agriculture_merchants_url)
    end
  end
end
