require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/agriculture_farms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AgricultureFarm. As you add validations to AgricultureFarm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AgricultureFarm.create! valid_attributes
      get agriculture_farms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      agriculture_farm = AgricultureFarm.create! valid_attributes
      get agriculture_farm_url(agriculture_farm)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_agriculture_farm_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      agriculture_farm = AgricultureFarm.create! valid_attributes
      get edit_agriculture_farm_url(agriculture_farm)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AgricultureFarm" do
        expect {
          post agriculture_farms_url, params: { agriculture_farm: valid_attributes }
        }.to change(AgricultureFarm, :count).by(1)
      end

      it "redirects to the created agriculture_farm" do
        post agriculture_farms_url, params: { agriculture_farm: valid_attributes }
        expect(response).to redirect_to(agriculture_farm_url(AgricultureFarm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AgricultureFarm" do
        expect {
          post agriculture_farms_url, params: { agriculture_farm: invalid_attributes }
        }.to change(AgricultureFarm, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post agriculture_farms_url, params: { agriculture_farm: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested agriculture_farm" do
        agriculture_farm = AgricultureFarm.create! valid_attributes
        patch agriculture_farm_url(agriculture_farm), params: { agriculture_farm: new_attributes }
        agriculture_farm.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the agriculture_farm" do
        agriculture_farm = AgricultureFarm.create! valid_attributes
        patch agriculture_farm_url(agriculture_farm), params: { agriculture_farm: new_attributes }
        agriculture_farm.reload
        expect(response).to redirect_to(agriculture_farm_url(agriculture_farm))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        agriculture_farm = AgricultureFarm.create! valid_attributes
        patch agriculture_farm_url(agriculture_farm), params: { agriculture_farm: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agriculture_farm" do
      agriculture_farm = AgricultureFarm.create! valid_attributes
      expect {
        delete agriculture_farm_url(agriculture_farm)
      }.to change(AgricultureFarm, :count).by(-1)
    end

    it "redirects to the agriculture_farms list" do
      agriculture_farm = AgricultureFarm.create! valid_attributes
      delete agriculture_farm_url(agriculture_farm)
      expect(response).to redirect_to(agriculture_farms_url)
    end
  end
end
