require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/article_comments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ArticleComment. As you add validations to ArticleComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ArticleComment.create! valid_attributes
      get article_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      article_comment = ArticleComment.create! valid_attributes
      get article_comment_url(article_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_article_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      article_comment = ArticleComment.create! valid_attributes
      get edit_article_comment_url(article_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ArticleComment" do
        expect {
          post article_comments_url, params: { article_comment: valid_attributes }
        }.to change(ArticleComment, :count).by(1)
      end

      it "redirects to the created article_comment" do
        post article_comments_url, params: { article_comment: valid_attributes }
        expect(response).to redirect_to(article_comment_url(ArticleComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ArticleComment" do
        expect {
          post article_comments_url, params: { article_comment: invalid_attributes }
        }.to change(ArticleComment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post article_comments_url, params: { article_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested article_comment" do
        article_comment = ArticleComment.create! valid_attributes
        patch article_comment_url(article_comment), params: { article_comment: new_attributes }
        article_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the article_comment" do
        article_comment = ArticleComment.create! valid_attributes
        patch article_comment_url(article_comment), params: { article_comment: new_attributes }
        article_comment.reload
        expect(response).to redirect_to(article_comment_url(article_comment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        article_comment = ArticleComment.create! valid_attributes
        patch article_comment_url(article_comment), params: { article_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested article_comment" do
      article_comment = ArticleComment.create! valid_attributes
      expect {
        delete article_comment_url(article_comment)
      }.to change(ArticleComment, :count).by(-1)
    end

    it "redirects to the article_comments list" do
      article_comment = ArticleComment.create! valid_attributes
      delete article_comment_url(article_comment)
      expect(response).to redirect_to(article_comments_url)
    end
  end
end
