require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bloggers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Blogger. As you add validations to Blogger, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Blogger.create! valid_attributes
      get bloggers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blogger = Blogger.create! valid_attributes
      get blogger_url(blogger)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blogger_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      blogger = Blogger.create! valid_attributes
      get edit_blogger_url(blogger)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Blogger" do
        expect {
          post bloggers_url, params: { blogger: valid_attributes }
        }.to change(Blogger, :count).by(1)
      end

      it "redirects to the created blogger" do
        post bloggers_url, params: { blogger: valid_attributes }
        expect(response).to redirect_to(blogger_url(Blogger.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Blogger" do
        expect {
          post bloggers_url, params: { blogger: invalid_attributes }
        }.to change(Blogger, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bloggers_url, params: { blogger: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blogger" do
        blogger = Blogger.create! valid_attributes
        patch blogger_url(blogger), params: { blogger: new_attributes }
        blogger.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blogger" do
        blogger = Blogger.create! valid_attributes
        patch blogger_url(blogger), params: { blogger: new_attributes }
        blogger.reload
        expect(response).to redirect_to(blogger_url(blogger))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        blogger = Blogger.create! valid_attributes
        patch blogger_url(blogger), params: { blogger: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blogger" do
      blogger = Blogger.create! valid_attributes
      expect {
        delete blogger_url(blogger)
      }.to change(Blogger, :count).by(-1)
    end

    it "redirects to the bloggers list" do
      blogger = Blogger.create! valid_attributes
      delete blogger_url(blogger)
      expect(response).to redirect_to(bloggers_url)
    end
  end
end
