require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/car_cars", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CarCar. As you add validations to CarCar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CarCar.create! valid_attributes
      get car_cars_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      car_car = CarCar.create! valid_attributes
      get car_car_url(car_car)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_car_car_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      car_car = CarCar.create! valid_attributes
      get edit_car_car_url(car_car)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CarCar" do
        expect {
          post car_cars_url, params: { car_car: valid_attributes }
        }.to change(CarCar, :count).by(1)
      end

      it "redirects to the created car_car" do
        post car_cars_url, params: { car_car: valid_attributes }
        expect(response).to redirect_to(car_car_url(CarCar.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CarCar" do
        expect {
          post car_cars_url, params: { car_car: invalid_attributes }
        }.to change(CarCar, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post car_cars_url, params: { car_car: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested car_car" do
        car_car = CarCar.create! valid_attributes
        patch car_car_url(car_car), params: { car_car: new_attributes }
        car_car.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the car_car" do
        car_car = CarCar.create! valid_attributes
        patch car_car_url(car_car), params: { car_car: new_attributes }
        car_car.reload
        expect(response).to redirect_to(car_car_url(car_car))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        car_car = CarCar.create! valid_attributes
        patch car_car_url(car_car), params: { car_car: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested car_car" do
      car_car = CarCar.create! valid_attributes
      expect {
        delete car_car_url(car_car)
      }.to change(CarCar, :count).by(-1)
    end

    it "redirects to the car_cars list" do
      car_car = CarCar.create! valid_attributes
      delete car_car_url(car_car)
      expect(response).to redirect_to(car_cars_url)
    end
  end
end
