require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/vehicle_stores", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # VehicleStore. As you add validations to VehicleStore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      VehicleStore.create! valid_attributes
      get vehicle_stores_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      vehicle_store = VehicleStore.create! valid_attributes
      get vehicle_store_url(vehicle_store)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_vehicle_store_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      vehicle_store = VehicleStore.create! valid_attributes
      get edit_vehicle_store_url(vehicle_store)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VehicleStore" do
        expect {
          post vehicle_stores_url, params: { vehicle_store: valid_attributes }
        }.to change(VehicleStore, :count).by(1)
      end

      it "redirects to the created vehicle_store" do
        post vehicle_stores_url, params: { vehicle_store: valid_attributes }
        expect(response).to redirect_to(vehicle_store_url(VehicleStore.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VehicleStore" do
        expect {
          post vehicle_stores_url, params: { vehicle_store: invalid_attributes }
        }.to change(VehicleStore, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post vehicle_stores_url, params: { vehicle_store: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vehicle_store" do
        vehicle_store = VehicleStore.create! valid_attributes
        patch vehicle_store_url(vehicle_store), params: { vehicle_store: new_attributes }
        vehicle_store.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the vehicle_store" do
        vehicle_store = VehicleStore.create! valid_attributes
        patch vehicle_store_url(vehicle_store), params: { vehicle_store: new_attributes }
        vehicle_store.reload
        expect(response).to redirect_to(vehicle_store_url(vehicle_store))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        vehicle_store = VehicleStore.create! valid_attributes
        patch vehicle_store_url(vehicle_store), params: { vehicle_store: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested vehicle_store" do
      vehicle_store = VehicleStore.create! valid_attributes
      expect {
        delete vehicle_store_url(vehicle_store)
      }.to change(VehicleStore, :count).by(-1)
    end

    it "redirects to the vehicle_stores list" do
      vehicle_store = VehicleStore.create! valid_attributes
      delete vehicle_store_url(vehicle_store)
      expect(response).to redirect_to(vehicle_stores_url)
    end
  end
end
