require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/car_brands", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CarBrand. As you add validations to CarBrand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CarBrand.create! valid_attributes
      get car_brands_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      car_brand = CarBrand.create! valid_attributes
      get car_brand_url(car_brand)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_car_brand_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      car_brand = CarBrand.create! valid_attributes
      get edit_car_brand_url(car_brand)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CarBrand" do
        expect {
          post car_brands_url, params: { car_brand: valid_attributes }
        }.to change(CarBrand, :count).by(1)
      end

      it "redirects to the created car_brand" do
        post car_brands_url, params: { car_brand: valid_attributes }
        expect(response).to redirect_to(car_brand_url(CarBrand.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CarBrand" do
        expect {
          post car_brands_url, params: { car_brand: invalid_attributes }
        }.to change(CarBrand, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post car_brands_url, params: { car_brand: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested car_brand" do
        car_brand = CarBrand.create! valid_attributes
        patch car_brand_url(car_brand), params: { car_brand: new_attributes }
        car_brand.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the car_brand" do
        car_brand = CarBrand.create! valid_attributes
        patch car_brand_url(car_brand), params: { car_brand: new_attributes }
        car_brand.reload
        expect(response).to redirect_to(car_brand_url(car_brand))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        car_brand = CarBrand.create! valid_attributes
        patch car_brand_url(car_brand), params: { car_brand: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested car_brand" do
      car_brand = CarBrand.create! valid_attributes
      expect {
        delete car_brand_url(car_brand)
      }.to change(CarBrand, :count).by(-1)
    end

    it "redirects to the car_brands list" do
      car_brand = CarBrand.create! valid_attributes
      delete car_brand_url(car_brand)
      expect(response).to redirect_to(car_brands_url)
    end
  end
end
