require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chat_messages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ChatMessage. As you add validations to ChatMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChatMessage.create! valid_attributes
      get chat_messages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chat_message = ChatMessage.create! valid_attributes
      get chat_message_url(chat_message)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chat_message_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      chat_message = ChatMessage.create! valid_attributes
      get edit_chat_message_url(chat_message)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChatMessage" do
        expect {
          post chat_messages_url, params: { chat_message: valid_attributes }
        }.to change(ChatMessage, :count).by(1)
      end

      it "redirects to the created chat_message" do
        post chat_messages_url, params: { chat_message: valid_attributes }
        expect(response).to redirect_to(chat_message_url(ChatMessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChatMessage" do
        expect {
          post chat_messages_url, params: { chat_message: invalid_attributes }
        }.to change(ChatMessage, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post chat_messages_url, params: { chat_message: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chat_message" do
        chat_message = ChatMessage.create! valid_attributes
        patch chat_message_url(chat_message), params: { chat_message: new_attributes }
        chat_message.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chat_message" do
        chat_message = ChatMessage.create! valid_attributes
        patch chat_message_url(chat_message), params: { chat_message: new_attributes }
        chat_message.reload
        expect(response).to redirect_to(chat_message_url(chat_message))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        chat_message = ChatMessage.create! valid_attributes
        patch chat_message_url(chat_message), params: { chat_message: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chat_message" do
      chat_message = ChatMessage.create! valid_attributes
      expect {
        delete chat_message_url(chat_message)
      }.to change(ChatMessage, :count).by(-1)
    end

    it "redirects to the chat_messages list" do
      chat_message = ChatMessage.create! valid_attributes
      delete chat_message_url(chat_message)
      expect(response).to redirect_to(chat_messages_url)
    end
  end
end
