require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/education_classes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EducationClass. As you add validations to EducationClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EducationClass.create! valid_attributes
      get education_classes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      education_class = EducationClass.create! valid_attributes
      get education_class_url(education_class)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_education_class_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      education_class = EducationClass.create! valid_attributes
      get edit_education_class_url(education_class)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EducationClass" do
        expect {
          post education_classes_url, params: { education_class: valid_attributes }
        }.to change(EducationClass, :count).by(1)
      end

      it "redirects to the created education_class" do
        post education_classes_url, params: { education_class: valid_attributes }
        expect(response).to redirect_to(education_class_url(EducationClass.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EducationClass" do
        expect {
          post education_classes_url, params: { education_class: invalid_attributes }
        }.to change(EducationClass, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post education_classes_url, params: { education_class: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested education_class" do
        education_class = EducationClass.create! valid_attributes
        patch education_class_url(education_class), params: { education_class: new_attributes }
        education_class.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the education_class" do
        education_class = EducationClass.create! valid_attributes
        patch education_class_url(education_class), params: { education_class: new_attributes }
        education_class.reload
        expect(response).to redirect_to(education_class_url(education_class))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        education_class = EducationClass.create! valid_attributes
        patch education_class_url(education_class), params: { education_class: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested education_class" do
      education_class = EducationClass.create! valid_attributes
      expect {
        delete education_class_url(education_class)
      }.to change(EducationClass, :count).by(-1)
    end

    it "redirects to the education_classes list" do
      education_class = EducationClass.create! valid_attributes
      delete education_class_url(education_class)
      expect(response).to redirect_to(education_classes_url)
    end
  end
end
