require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/education_schools", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EducationSchool. As you add validations to EducationSchool, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EducationSchool.create! valid_attributes
      get education_schools_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      education_school = EducationSchool.create! valid_attributes
      get education_school_url(education_school)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_education_school_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      education_school = EducationSchool.create! valid_attributes
      get edit_education_school_url(education_school)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EducationSchool" do
        expect {
          post education_schools_url, params: { education_school: valid_attributes }
        }.to change(EducationSchool, :count).by(1)
      end

      it "redirects to the created education_school" do
        post education_schools_url, params: { education_school: valid_attributes }
        expect(response).to redirect_to(education_school_url(EducationSchool.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EducationSchool" do
        expect {
          post education_schools_url, params: { education_school: invalid_attributes }
        }.to change(EducationSchool, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post education_schools_url, params: { education_school: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested education_school" do
        education_school = EducationSchool.create! valid_attributes
        patch education_school_url(education_school), params: { education_school: new_attributes }
        education_school.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the education_school" do
        education_school = EducationSchool.create! valid_attributes
        patch education_school_url(education_school), params: { education_school: new_attributes }
        education_school.reload
        expect(response).to redirect_to(education_school_url(education_school))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        education_school = EducationSchool.create! valid_attributes
        patch education_school_url(education_school), params: { education_school: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested education_school" do
      education_school = EducationSchool.create! valid_attributes
      expect {
        delete education_school_url(education_school)
      }.to change(EducationSchool, :count).by(-1)
    end

    it "redirects to the education_schools list" do
      education_school = EducationSchool.create! valid_attributes
      delete education_school_url(education_school)
      expect(response).to redirect_to(education_schools_url)
    end
  end
end
