require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/education_teachers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EducationTeacher. As you add validations to EducationTeacher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EducationTeacher.create! valid_attributes
      get education_teachers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      education_teacher = EducationTeacher.create! valid_attributes
      get education_teacher_url(education_teacher)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_education_teacher_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      education_teacher = EducationTeacher.create! valid_attributes
      get edit_education_teacher_url(education_teacher)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EducationTeacher" do
        expect {
          post education_teachers_url, params: { education_teacher: valid_attributes }
        }.to change(EducationTeacher, :count).by(1)
      end

      it "redirects to the created education_teacher" do
        post education_teachers_url, params: { education_teacher: valid_attributes }
        expect(response).to redirect_to(education_teacher_url(EducationTeacher.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EducationTeacher" do
        expect {
          post education_teachers_url, params: { education_teacher: invalid_attributes }
        }.to change(EducationTeacher, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post education_teachers_url, params: { education_teacher: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested education_teacher" do
        education_teacher = EducationTeacher.create! valid_attributes
        patch education_teacher_url(education_teacher), params: { education_teacher: new_attributes }
        education_teacher.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the education_teacher" do
        education_teacher = EducationTeacher.create! valid_attributes
        patch education_teacher_url(education_teacher), params: { education_teacher: new_attributes }
        education_teacher.reload
        expect(response).to redirect_to(education_teacher_url(education_teacher))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        education_teacher = EducationTeacher.create! valid_attributes
        patch education_teacher_url(education_teacher), params: { education_teacher: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested education_teacher" do
      education_teacher = EducationTeacher.create! valid_attributes
      expect {
        delete education_teacher_url(education_teacher)
      }.to change(EducationTeacher, :count).by(-1)
    end

    it "redirects to the education_teachers list" do
      education_teacher = EducationTeacher.create! valid_attributes
      delete education_teacher_url(education_teacher)
      expect(response).to redirect_to(education_teachers_url)
    end
  end
end
