require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/education_students", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EducationStudent. As you add validations to EducationStudent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EducationStudent.create! valid_attributes
      get education_students_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      education_student = EducationStudent.create! valid_attributes
      get education_student_url(education_student)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_education_student_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      education_student = EducationStudent.create! valid_attributes
      get edit_education_student_url(education_student)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EducationStudent" do
        expect {
          post education_students_url, params: { education_student: valid_attributes }
        }.to change(EducationStudent, :count).by(1)
      end

      it "redirects to the created education_student" do
        post education_students_url, params: { education_student: valid_attributes }
        expect(response).to redirect_to(education_student_url(EducationStudent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EducationStudent" do
        expect {
          post education_students_url, params: { education_student: invalid_attributes }
        }.to change(EducationStudent, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post education_students_url, params: { education_student: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested education_student" do
        education_student = EducationStudent.create! valid_attributes
        patch education_student_url(education_student), params: { education_student: new_attributes }
        education_student.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the education_student" do
        education_student = EducationStudent.create! valid_attributes
        patch education_student_url(education_student), params: { education_student: new_attributes }
        education_student.reload
        expect(response).to redirect_to(education_student_url(education_student))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        education_student = EducationStudent.create! valid_attributes
        patch education_student_url(education_student), params: { education_student: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested education_student" do
      education_student = EducationStudent.create! valid_attributes
      expect {
        delete education_student_url(education_student)
      }.to change(EducationStudent, :count).by(-1)
    end

    it "redirects to the education_students list" do
      education_student = EducationStudent.create! valid_attributes
      delete education_student_url(education_student)
      expect(response).to redirect_to(education_students_url)
    end
  end
end
