require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/english_meanings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EnglishMeaning. As you add validations to EnglishMeaning, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EnglishMeaning.create! valid_attributes
      get english_meanings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      english_meaning = EnglishMeaning.create! valid_attributes
      get english_meaning_url(english_meaning)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_english_meaning_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      english_meaning = EnglishMeaning.create! valid_attributes
      get edit_english_meaning_url(english_meaning)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EnglishMeaning" do
        expect {
          post english_meanings_url, params: { english_meaning: valid_attributes }
        }.to change(EnglishMeaning, :count).by(1)
      end

      it "redirects to the created english_meaning" do
        post english_meanings_url, params: { english_meaning: valid_attributes }
        expect(response).to redirect_to(english_meaning_url(EnglishMeaning.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EnglishMeaning" do
        expect {
          post english_meanings_url, params: { english_meaning: invalid_attributes }
        }.to change(EnglishMeaning, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post english_meanings_url, params: { english_meaning: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested english_meaning" do
        english_meaning = EnglishMeaning.create! valid_attributes
        patch english_meaning_url(english_meaning), params: { english_meaning: new_attributes }
        english_meaning.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the english_meaning" do
        english_meaning = EnglishMeaning.create! valid_attributes
        patch english_meaning_url(english_meaning), params: { english_meaning: new_attributes }
        english_meaning.reload
        expect(response).to redirect_to(english_meaning_url(english_meaning))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        english_meaning = EnglishMeaning.create! valid_attributes
        patch english_meaning_url(english_meaning), params: { english_meaning: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested english_meaning" do
      english_meaning = EnglishMeaning.create! valid_attributes
      expect {
        delete english_meaning_url(english_meaning)
      }.to change(EnglishMeaning, :count).by(-1)
    end

    it "redirects to the english_meanings list" do
      english_meaning = EnglishMeaning.create! valid_attributes
      delete english_meaning_url(english_meaning)
      expect(response).to redirect_to(english_meanings_url)
    end
  end
end
