require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/review_comments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ReviewComment. As you add validations to ReviewComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReviewComment.create! valid_attributes
      get review_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      review_comment = ReviewComment.create! valid_attributes
      get review_comment_url(review_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_review_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      review_comment = ReviewComment.create! valid_attributes
      get edit_review_comment_url(review_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReviewComment" do
        expect {
          post review_comments_url, params: { review_comment: valid_attributes }
        }.to change(ReviewComment, :count).by(1)
      end

      it "redirects to the created review_comment" do
        post review_comments_url, params: { review_comment: valid_attributes }
        expect(response).to redirect_to(review_comment_url(ReviewComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReviewComment" do
        expect {
          post review_comments_url, params: { review_comment: invalid_attributes }
        }.to change(ReviewComment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post review_comments_url, params: { review_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested review_comment" do
        review_comment = ReviewComment.create! valid_attributes
        patch review_comment_url(review_comment), params: { review_comment: new_attributes }
        review_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the review_comment" do
        review_comment = ReviewComment.create! valid_attributes
        patch review_comment_url(review_comment), params: { review_comment: new_attributes }
        review_comment.reload
        expect(response).to redirect_to(review_comment_url(review_comment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        review_comment = ReviewComment.create! valid_attributes
        patch review_comment_url(review_comment), params: { review_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested review_comment" do
      review_comment = ReviewComment.create! valid_attributes
      expect {
        delete review_comment_url(review_comment)
      }.to change(ReviewComment, :count).by(-1)
    end

    it "redirects to the review_comments list" do
      review_comment = ReviewComment.create! valid_attributes
      delete review_comment_url(review_comment)
      expect(response).to redirect_to(review_comments_url)
    end
  end
end
