module Constants
  WEBSOCKET_HOST = ENV.fetch('KAMAL_WEBSOCKET_HOST') { "0.0.0.0" }
  WEBSOCKET_PORT = ENV.fetch('KAMAL_WEBSOCKET_PORT') { "8080" }
  WEBSOCKET_URL = WEBSOCKET_HOST + ':' + WEBSOCKET_PORT

  SIDEKIQ_UI_USERNAME = ENV.fetch('SIDEKIQ_UI_USERNAME') { "admin" }
  SIDEKIQ_UI_PASSWORD = ENV.fetch('SIDEKIQ_UI_PASSWORD') { "password" }
end