module Constants
  WEBSOCKET_HOST = ENV.fetch('KAMAL_WEBSOCKET_HOST') { "0.0.0.0" }
  WEBSOCKET_PORT = ENV.fetch('KAMAL_WEBSOCKET_PORT') { "8080" }
  WEBSOCKET_URL = WEBSOCKET_HOST + ':' + WEBSOCKET_PORT

  SIDEKIQ_UI_USER = ENV.fetch('SIDEKIQ_UI_USER') { "admin" }
  SIDEKIQ_UI_PASSWORD = ENV.fetch('SIDEKIQ_UI_PASSWORD') { "password" }

  JWT_ACCESS_EXPIRATION = ENV.fetch('JWT_ACCESS_EXPIRATION') { "1" }
  JWT_REFRESH_EXPIRATION = ENV.fetch('JWT_REFRESH_EXPIRATION') { "10" }
end
TrueOrFalse = ActiveModel::Type::Boolean.new