# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Logo::DiscordComponent`.
# Please instead update this file by running `bin/tapioca dsl Logo::DiscordComponent`.

class Logo::DiscordComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
