# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Logo::GithubComponent`.
# Please instead update this file by running `bin/tapioca dsl Logo::GithubComponent`.

class Logo::GithubComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
