# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Logo::YoutubeComponent`.
# Please instead update this file by running `bin/tapioca dsl Logo::YoutubeComponent`.

class Logo::YoutubeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
