# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::FloatingFillComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::FloatingFillComponent`.

class Input::FloatingFillComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
