# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::FloatingOutlineComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::FloatingOutlineComponent`.

class Input::FloatingOutlineComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
