# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::FloatingStandardComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::FloatingStandardComponent`.

class Input::FloatingStandardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
