# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::PinCodeComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::PinCodeComponent`.

class Input::PinCodeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
