# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Dropdown::LanguageComponent`.
# Please instead update this file by running `bin/tapioca dsl Dropdown::LanguageComponent`.

class Dropdown::LanguageComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
