# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or "" in any view
# to make the web console appear.

# solid_cable setup
default: &default
  adapter: solid_cable
  polling_interval: 1.second
  keep_messages_around_for: 1.day

development:
  <<: *default
  silence_polling: true
  connects_to:
    database:
      writing: cable
      reading: cable

test:
  adapter: test
  # adapter: async

production:
  <<: *default
  polling_interval: 0.1.seconds
  connects_to:
    database:
      writing: cable
      reading: cable


# redis setup
# development:
#   adapter: redis
#   # url: redis://localhost:6379/1
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>


# test:
#   adapter: test

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: skyceer_production