sqlite3: &sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "0.0.0.0" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

queue: &queue
  <<: *postgresql
  migrations_paths: db/queue_migrate

cable: &cable
  <<: *sqlite3
  migrations_paths: db/cable_migrate

cache: &cache
  <<: *sqlite3
  migrations_paths: db/cache_migrate

development:
  primary:
    <<: *postgresql
    database: skyceer_development
  queue:
    <<: *queue
    database: queue_development
  cable:
    <<: *cable
    database: storage/development_cable.sqlite3
  cache:
    <<: *cache
    database: storage/development_cache.sqlite3
    
test:
  primary:
    <<: *postgresql
    database: skyceer_test
  queue:
    <<: *queue
    database: queue_test
  cable:
    <<: *cable
    database: storage/test_cable.sqlite3
  cache:
    <<: *cache
    database: storage/test_cache.sqlite3

production:
  primary:
    <<: *postgresql
    database: skyceer_production
  queue:
    <<: *queue
    database: queue_production
  cable:
    <<: *cable
    database: storage/production_cable.sqlite3
  cache:
    <<: *cache
    database: storage/production_cache.sqlite3
