default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "0.0.0.0" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

session: &session
  <<: *default
  migrations_paths: db/session_migrate

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate

development:
  primary:
    <<: *default
    database: skyceer_development
  session:
    <<: *session
    database: session_development
  queue:
    <<: *queue
    database: queue_development
  cable:
    <<: *cable
    database: cable_development
  cache:
    <<: *cache
    database: cache_development
    
test:
  primary:
    <<: *default
    database: skyceer_test
  session:
    <<: *session
    database: session_test
  queue:
    <<: *queue
    database: queue_test
  cable:
    <<: *cable
    database: cable_test
  cache:
    <<: *cache
    database: cache_test

production:
  primary:
    <<: *default
    database: skyceer_production
  session:
    <<: *session
    database: session_production
  queue:
    <<: *queue
    database: queue_production
  cable:
    <<: *cable
    database: cable_production
  cache:
    <<: *cache
    database: cache_production
