default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: <%= ENV.fetch("POSTGRES_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "0.0.0.0" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

session: &session
  <<: *default
  migrations_paths: db/session_migrate

solid: &solid
  <<: *default
  migrations_paths: db/solid_migrate

development:
  primary:
    <<: *default
    database: skyceer_development
  session:
    <<: *session
    database: session_development
  solid:
    <<: *solid
    database: solid_development
    
test:
  primary:
    <<: *default
    database: skyceer_test
  session:
    <<: *session
    database: session_test
  solid:
    <<: *solid
    database: solid_test

production:
  primary:
    <<: *default
    database: skyceer_development
  session:
    <<: *session
    database: session_development
  solid:
    <<: *solid
    database: solid_development
