# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Header::StickyComponent`.
# Please instead update this file by running `bin/tapioca dsl Header::StickyComponent`.

class Header::StickyComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
