import { Addresses_US } from "./us"
import { Addresses_Vietnam } from "./vietname"

export const Countries = [
  { name: "Afghanistan", iso2: "AF", iso3: "AFG", numeric: "004", address: {} },
  { name: "Albania", iso2: "AL", iso3: "ALB", numeric: "008", address: {} },
  { name: "Algeria", iso2: "DZ", iso3: "DZA", numeric: "012", address: {} },
  { name: "American Samoa", iso2: "AS", iso3: "ASM", numeric: "016", address: {} },
  { name: "Andorra", iso2: "AD", iso3: "AND", numeric: "020", address: {} },
  { name: "Angola", iso2: "AO", iso3: "AGO", numeric: "024", address: {} },
  { name: "Anguilla", iso2: "AI", iso3: "AIA", numeric: "660", address: {} },
  { name: "Antarctica", iso2: "AQ", iso3: "ATA", numeric: "010", address: {} },
  { name: "Antigua and Barbuda", iso2: "AG", iso3: "ATG", numeric: "028", address: {} },
  { name: "Argentina", iso2: "AR", iso3: "ARG", numeric: "032", address: {} },
  { name: "Armenia", iso2: "AM", iso3: "ARM", numeric: "051", address: {} },
  { name: "Aruba", iso2: "AW", iso3: "ABW", numeric: "533", address: {} },
  { name: "Australia", iso2: "AU", iso3: "AUS", numeric: "036", address: {} },
  { name: "Austria", iso2: "AT", iso3: "AUT", numeric: "040", address: {} },
  { name: "Azerbaijan", iso2: "AZ", iso3: "AZE", numeric: "031", address: {} },
  { name: "Bahamas (the)", iso2: "BS", iso3: "BHS", numeric: "044", address: {} },
  { name: "Bahrain", iso2: "BH", iso3: "BHR", numeric: "048", address: {} },
  { name: "Bangladesh", iso2: "BD", iso3: "BGD", numeric: "050", address: {} },
  { name: "Barbados", iso2: "BB", iso3: "BRB", numeric: "052", address: {} },
  { name: "Belarus", iso2: "BY", iso3: "BLR", numeric: "112", address: {} },
  { name: "Belgium", iso2: "BE", iso3: "BEL", numeric: "056", address: {} },
  { name: "Belize", iso2: "BZ", iso3: "BLZ", numeric: "084", address: {} },
  { name: "Benin", iso2: "BJ", iso3: "BEN", numeric: "204", address: {} },
  { name: "Bermuda", iso2: "BM", iso3: "BMU", numeric: "060", address: {} },
  { name: "Bhutan", iso2: "BT", iso3: "BTN", numeric: "064", address: {} },
  { name: "Bolivia (Plurinational State of)", iso2: "BO", iso3: "BOL", numeric: "068", address: {} },
  { name: "Bonaire, Sint Eustatius and Saba", iso2: "BQ", iso3: "BES", numeric: "535", address: {} },
  { name: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", numeric: "070", address: {} },
  { name: "Botswana", iso2: "BW", iso3: "BWA", numeric: "072", address: {} },
  { name: "Bouvet Island", iso2: "BV", iso3: "BVT", numeric: "074", address: {} },
  { name: "Brazil", iso2: "BR", iso3: "BRA", numeric: "076", address: {} },
  { name: "British Indian Ocean Territory (the)", iso2: "IO", iso3: "IOT", numeric: "086", address: {} },
  { name: "Brunei Darussalam", iso2: "BN", iso3: "BRN", numeric: "096", address: {} },
  { name: "Bulgaria", iso2: "BG", iso3: "BGR", numeric: "100", address: {} },
  { name: "Burkina Faso", iso2: "BF", iso3: "BFA", numeric: "854", address: {} },
  { name: "Burundi", iso2: "BI", iso3: "BDI", numeric: "108", address: {} },
  { name: "Cabo Verde", iso2: "CV", iso3: "CPV", numeric: "132", address: {} },
  { name: "Cambodia", iso2: "KH", iso3: "KHM", numeric: "116", address: {} },
  { name: "Cameroon", iso2: "CM", iso3: "CMR", numeric: "120", address: {} },
  { name: "Canada", iso2: "CA", iso3: "CAN", numeric: "124", address: {} },
  { name: "Cayman Islands (the)", iso2: "KY", iso3: "CYM", numeric: "136", address: {} },
  { name: "Central African Republic (the)", iso2: "CF", iso3: "CAF", numeric: "140", address: {} },
  { name: "Chad", iso2: "TD", iso3: "TCD", numeric: "148", address: {} },
  { name: "Chile", iso2: "CL", iso3: "CHL", numeric: "152", address: {} },
  { name: "China", iso2: "CN", iso3: "CHN", numeric: "156", address: {} },
  { name: "Christmas Island", iso2: "CX", iso3: "CXR", numeric: "162", address: {} },
  { name: "Cocos (Keeling) Islands (the)", iso2: "CC", iso3: "CCK", numeric: "166", address: {} },
  { name: "Colombia", iso2: "CO", iso3: "COL", numeric: "170", address: {} },
  { name: "Comoros (the)", iso2: "KM", iso3: "COM", numeric: "174", address: {} },
  { name: "Congo (the Democratic Republic of the)", iso2: "CD", iso3: "COD", numeric: "180", address: {} },
  { name: "Congo (the)", iso2: "CG", iso3: "COG", numeric: "178", address: {} },
  { name: "Cook Islands (the)", iso2: "CK", iso3: "COK", numeric: "184", address: {} },
  { name: "Costa Rica", iso2: "CR", iso3: "CRI", numeric: "188", address: {} },
  { name: "Croatia", iso2: "HR", iso3: "HRV", numeric: "191", address: {} },
  { name: "Cuba", iso2: "CU", iso3: "CUB", numeric: "192", address: {} },
  { name: "Curaçao", iso2: "CW", iso3: "CUW", numeric: "531", address: {} },
  { name: "Cyprus", iso2: "CY", iso3: "CYP", numeric: "196", address: {} },
  { name: "Czechia", iso2: "CZ", iso3: "CZE", numeric: "203", address: {} },
  { name: "Côte d'Ivoire", iso2: "CI", iso3: "CIV", numeric: "384", address: {} },
  { name: "Denmark", iso2: "DK", iso3: "DNK", numeric: "208", address: {} },
  { name: "Djibouti", iso2: "DJ", iso3: "DJI", numeric: "262", address: {} },
  { name: "Dominica", iso2: "DM", iso3: "DMA", numeric: "212", address: {} },
  { name: "Dominican Republic (the)", iso2: "DO", iso3: "DOM", numeric: "214", address: {} },
  { name: "Ecuador", iso2: "EC", iso3: "ECU", numeric: "218", address: {} },
  { name: "Egypt", iso2: "EG", iso3: "EGY", numeric: "818", address: {} },
  { name: "El Salvador", iso2: "SV", iso3: "SLV", numeric: "222", address: {} },
  { name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", numeric: "226", address: {} },
  { name: "Eritrea", iso2: "ER", iso3: "ERI", numeric: "232", address: {} },
  { name: "Estonia", iso2: "EE", iso3: "EST", numeric: "233", address: {} },
  { name: "Eswatini", iso2: "SZ", iso3: "SWZ", numeric: "748", address: {} },
  { name: "Ethiopia", iso2: "ET", iso3: "ETH", numeric: "231", address: {} },
  { name: "Falkland Islands (the) [Malvinas]", iso2: "FK", iso3: "FLK", numeric: "238", address: {} },
  { name: "Faroe Islands (the)", iso2: "FO", iso3: "FRO", numeric: "234", address: {} },
  { name: "Fiji", iso2: "FJ", iso3: "FJI", numeric: "242", address: {} },
  { name: "Finland", iso2: "FI", iso3: "FIN", numeric: "246", address: {} },
  { name: "France", iso2: "FR", iso3: "FRA", numeric: "250", address: {} },
  { name: "French Guiana", iso2: "GF", iso3: "GUF", numeric: "254", address: {} },
  { name: "French Polynesia", iso2: "PF", iso3: "PYF", numeric: "258", address: {} },
  { name: "French Southern Territories (the)", iso2: "TF", iso3: "ATF", numeric: "260", address: {} },
  { name: "Gabon", iso2: "GA", iso3: "GAB", numeric: "266", address: {} },
  { name: "Gambia (the)", iso2: "GM", iso3: "GMB", numeric: "270", address: {} },
  { name: "Georgia", iso2: "GE", iso3: "GEO", numeric: "268", address: {} },
  { name: "Germany", iso2: "DE", iso3: "DEU", numeric: "276", address: {} },
  { name: "Ghana", iso2: "GH", iso3: "GHA", numeric: "288", address: {} },
  { name: "Gibraltar", iso2: "GI", iso3: "GIB", numeric: "292", address: {} },
  { name: "Greece", iso2: "GR", iso3: "GRC", numeric: "300", address: {} },
  { name: "Greenland", iso2: "GL", iso3: "GRL", numeric: "304", address: {} },
  { name: "Grenada", iso2: "GD", iso3: "GRD", numeric: "308", address: {} },
  { name: "Guadeloupe", iso2: "GP", iso3: "GLP", numeric: "312", address: {} },
  { name: "Guam", iso2: "GU", iso3: "GUM", numeric: "316", address: {} },
  { name: "Guatemala", iso2: "GT", iso3: "GTM", numeric: "320", address: {} },
  { name: "Guernsey", iso2: "GG", iso3: "GGY", numeric: "831", address: {} },
  { name: "Guinea", iso2: "GN", iso3: "GIN", numeric: "324", address: {} },
  { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB", numeric: "624", address: {} },
  { name: "Guyana", iso2: "GY", iso3: "GUY", numeric: "328", address: {} },
  { name: "Haiti", iso2: "HT", iso3: "HTI", numeric: "332", address: {} },
  { name: "Heard Island and McDonald Islands", iso2: "HM", iso3: "HMD", numeric: "334", address: {} },
  { name: "Holy See (the)", iso2: "VA", iso3: "VAT", numeric: "336", address: {} },
  { name: "Honduras", iso2: "HN", iso3: "HND", numeric: "340", address: {} },
  { name: "Hong Kong", iso2: "HK", iso3: "HKG", numeric: "344", address: {} },
  { name: "Hungary", iso2: "HU", iso3: "HUN", numeric: "348", address: {} },
  { name: "Iceland", iso2: "IS", iso3: "ISL", numeric: "352", address: {} },
  { name: "India", iso2: "IN", iso3: "IND", numeric: "356", address: {} },
  { name: "Indonesia", iso2: "ID", iso3: "IDN", numeric: "360", address: {} },
  { name: "Iran (Islamic Republic of)", iso2: "IR", iso3: "IRN", numeric: "364", address: {} },
  { name: "Iraq", iso2: "IQ", iso3: "IRQ", numeric: "368", address: {} },
  { name: "Ireland", iso2: "IE", iso3: "IRL", numeric: "372", address: {} },
  { name: "Isle of Man", iso2: "IM", iso3: "IMN", numeric: "833", address: {} },
  { name: "Israel", iso2: "IL", iso3: "ISR", numeric: "376", address: {} },
  { name: "Italy", iso2: "IT", iso3: "ITA", numeric: "380", address: {} },
  { name: "Jamaica", iso2: "JM", iso3: "JAM", numeric: "388", address: {} },
  { name: "Japan", iso2: "JP", iso3: "JPN", numeric: "392", address: {} },
  { name: "Jersey", iso2: "JE", iso3: "JEY", numeric: "832", address: {} },
  { name: "Jordan", iso2: "JO", iso3: "JOR", numeric: "400", address: {} },
  { name: "Kazakhstan", iso2: "KZ", iso3: "KAZ", numeric: "398", address: {} },
  { name: "Kenya", iso2: "KE", iso3: "KEN", numeric: "404", address: {} },
  { name: "Kiribati", iso2: "KI", iso3: "KIR", numeric: "296", address: {} },
  { name: "Korea (the Democratic People's Republic of)", iso2: "KP", iso3: "PRK", numeric: "408", address: {} },
  { name: "Korea (the Republic of)", iso2: "KR", iso3: "KOR", numeric: "410", address: {} },
  { name: "Kuwait", iso2: "KW", iso3: "KWT", numeric: "414", address: {} },
  { name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", numeric: "417", address: {} },
  { name: "Lao People's Democratic Republic (the)", iso2: "LA", iso3: "LAO", numeric: "418", address: {} },
  { name: "Latvia", iso2: "LV", iso3: "LVA", numeric: "428", address: {} },
  { name: "Lebanon", iso2: "LB", iso3: "LBN", numeric: "422", address: {} },
  { name: "Lesotho", iso2: "LS", iso3: "LSO", numeric: "426", address: {} },
  { name: "Liberia", iso2: "LR", iso3: "LBR", numeric: "430", address: {} },
  { name: "Libya", iso2: "LY", iso3: "LBY", numeric: "434", address: {} },
  { name: "Liechtenstein", iso2: "LI", iso3: "LIE", numeric: "438", address: {} },
  { name: "Lithuania", iso2: "LT", iso3: "LTU", numeric: "440", address: {} },
  { name: "Luxembourg", iso2: "LU", iso3: "LUX", numeric: "442", address: {} },
  { name: "Macao", iso2: "MO", iso3: "MAC", numeric: "446", address: {} },
  { name: "Madagascar", iso2: "MG", iso3: "MDG", numeric: "450", address: {} },
  { name: "Malawi", iso2: "MW", iso3: "MWI", numeric: "454", address: {} },
  { name: "Malaysia", iso2: "MY", iso3: "MYS", numeric: "458", address: {} },
  { name: "Maldives", iso2: "MV", iso3: "MDV", numeric: "462", address: {} },
  { name: "Mali", iso2: "ML", iso3: "MLI", numeric: "466", address: {} },
  { name: "Malta", iso2: "MT", iso3: "MLT", numeric: "470", address: {} },
  { name: "Marshall Islands (the)", iso2: "MH", iso3: "MHL", numeric: "584", address: {} },
  { name: "Martinique", iso2: "MQ", iso3: "MTQ", numeric: "474", address: {} },
  { name: "Mauritania", iso2: "MR", iso3: "MRT", numeric: "478", address: {} },
  { name: "Mauritius", iso2: "MU", iso3: "MUS", numeric: "480", address: {} },
  { name: "Mayotte", iso2: "YT", iso3: "MYT", numeric: "175", address: {} },
  { name: "Mexico", iso2: "MX", iso3: "MEX", numeric: "484", address: {} },
  { name: "Micronesia (Federated States of)", iso2: "FM", iso3: "FSM", numeric: "583", address: {} },
  { name: "Moldova (the Republic of)", iso2: "MD", iso3: "MDA", numeric: "498", address: {} },
  { name: "Monaco", iso2: "MC", iso3: "MCO", numeric: "492", address: {} },
  { name: "Mongolia", iso2: "MN", iso3: "MNG", numeric: "496", address: {} },
  { name: "Montenegro", iso2: "ME", iso3: "MNE", numeric: "499", address: {} },
  { name: "Montserrat", iso2: "MS", iso3: "MSR", numeric: "500", address: {} },
  { name: "Morocco", iso2: "MA", iso3: "MAR", numeric: "504", address: {} },
  { name: "Mozambique", iso2: "MZ", iso3: "MOZ", numeric: "508", address: {} },
  { name: "Myanmar", iso2: "MM", iso3: "MMR", numeric: "104", address: {} },
  { name: "Namibia", iso2: "NA", iso3: "NAM", numeric: "516", address: {} },
  { name: "Nauru", iso2: "NR", iso3: "NRU", numeric: "520", address: {} },
  { name: "Nepal", iso2: "NP", iso3: "NPL", numeric: "524", address: {} },
  { name: "Netherlands (the)", iso2: "NL", iso3: "NLD", numeric: "528", address: {} },
  { name: "New Caledonia", iso2: "NC", iso3: "NCL", numeric: "540", address: {} },
  { name: "New Zealand", iso2: "NZ", iso3: "NZL", numeric: "554", address: {} },
  { name: "Nicaragua", iso2: "NI", iso3: "NIC", numeric: "558", address: {} },
  { name: "Niger (the)", iso2: "NE", iso3: "NER", numeric: "562", address: {} },
  { name: "Nigeria", iso2: "NG", iso3: "NGA", numeric: "566", address: {} },
  { name: "Niue", iso2: "NU", iso3: "NIU", numeric: "570", address: {} },
  { name: "Norfolk Island", iso2: "NF", iso3: "NFK", numeric: "574", address: {} },
  { name: "Northern Mariana Islands (the)", iso2: "MP", iso3: "MNP", numeric: "580", address: {} },
  { name: "Norway", iso2: "NO", iso3: "NOR", numeric: "578", address: {} },
  { name: "Oman", iso2: "OM", iso3: "OMN", numeric: "512", address: {} },
  { name: "Pakistan", iso2: "PK", iso3: "PAK", numeric: "586", address: {} },
  { name: "Palau", iso2: "PW", iso3: "PLW", numeric: "585", address: {} },
  { name: "Palestine, State of", iso2: "PS", iso3: "PSE", numeric: "275", address: {} },
  { name: "Panama", iso2: "PA", iso3: "PAN", numeric: "591", address: {} },
  { name: "Papua New Guinea", iso2: "PG", iso3: "PNG", numeric: "598", address: {} },
  { name: "Paraguay", iso2: "PY", iso3: "PRY", numeric: "600", address: {} },
  { name: "Peru", iso2: "PE", iso3: "PER", numeric: "604", address: {} },
  { name: "Philippines (the)", iso2: "PH", iso3: "PHL", numeric: "608", address: {} },
  { name: "Pitcairn", iso2: "PN", iso3: "PCN", numeric: "612", address: {} },
  { name: "Poland", iso2: "PL", iso3: "POL", numeric: "616", address: {} },
  { name: "Portugal", iso2: "PT", iso3: "PRT", numeric: "620", address: {} },
  { name: "Puerto Rico", iso2: "PR", iso3: "PRI", numeric: "630", address: {} },
  { name: "Qatar", iso2: "QA", iso3: "QAT", numeric: "634", address: {} },
  { name: "Republic of North Macedonia", iso2: "MK", iso3: "MKD", numeric: "807", address: {} },
  { name: "Romania", iso2: "RO", iso3: "ROU", numeric: "642", address: {} },
  { name: "Russian Federation (the)", iso2: "RU", iso3: "RUS", numeric: "643", address: {} },
  { name: "Rwanda", iso2: "RW", iso3: "RWA", numeric: "646", address: {} },
  { name: "Réunion", iso2: "RE", iso3: "REU", numeric: "638", address: {} },
  { name: "Saint Barthélemy", iso2: "BL", iso3: "BLM", numeric: "652", address: {} },
  { name: "Saint Helena, Ascension and Tristan da Cunha", iso2: "SH", iso3: "SHN", numeric: "654", address: {} },
  { name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", numeric: "659", address: {} },
  { name: "Saint Lucia", iso2: "LC", iso3: "LCA", numeric: "662", address: {} },
  { name: "Saint Martin (French part)", iso2: "MF", iso3: "MAF", numeric: "663", address: {} },
  { name: "Saint Pierre and Miquelon", iso2: "PM", iso3: "SPM", numeric: "666", address: {} },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT", numeric: "670", address: {} },
  { name: "Samoa", iso2: "WS", iso3: "WSM", numeric: "882", address: {} },
  { name: "San Marino", iso2: "SM", iso3: "SMR", numeric: "674", address: {} },
  { name: "Sao Tome and Principe", iso2: "ST", iso3: "STP", numeric: "678", address: {} },
  { name: "Saudi Arabia", iso2: "SA", iso3: "SAU", numeric: "682", address: {} },
  { name: "Senegal", iso2: "SN", iso3: "SEN", numeric: "686", address: {} },
  { name: "Serbia", iso2: "RS", iso3: "SRB", numeric: "688", address: {} },
  { name: "Seychelles", iso2: "SC", iso3: "SYC", numeric: "690", address: {} },
  { name: "Sierra Leone", iso2: "SL", iso3: "SLE", numeric: "694", address: {} },
  { name: "Singapore", iso2: "SG", iso3: "SGP", numeric: "702", address: {} },
  { name: "Sint Maarten (Dutch part)", iso2: "SX", iso3: "SXM", numeric: "534", address: {} },
  { name: "Slovakia", iso2: "SK", iso3: "SVK", numeric: "703", address: {} },
  { name: "Slovenia", iso2: "SI", iso3: "SVN", numeric: "705", address: {} },
  { name: "Solomon Islands", iso2: "SB", iso3: "SLB", numeric: "090", address: {} },
  { name: "Somalia", iso2: "SO", iso3: "SOM", numeric: "706", address: {} },
  { name: "South Africa", iso2: "ZA", iso3: "ZAF", numeric: "710", address: {} },
  { name: "South Georgia and the South Sandwich Islands", iso2: "GS", iso3: "SGS", numeric: "239", address: {} },
  { name: "South Sudan", iso2: "SS", iso3: "SSD", numeric: "728", address: {} },
  { name: "Spain", iso2: "ES", iso3: "ESP", numeric: "724", address: {} },
  { name: "Sri Lanka", iso2: "LK", iso3: "LKA", numeric: "144", address: {} },
  { name: "Sudan (the)", iso2: "SD", iso3: "SDN", numeric: "729", address: {} },
  { name: "Suriname", iso2: "SR", iso3: "SUR", numeric: "740", address: {} },
  { name: "Svalbard and Jan Mayen", iso2: "SJ", iso3: "SJM", numeric: "744", address: {} },
  { name: "Sweden", iso2: "SE", iso3: "SWE", numeric: "752", address: {} },
  { name: "Switzerland", iso2: "CH", iso3: "CHE", numeric: "756", address: {} },
  { name: "Syrian Arab Republic", iso2: "SY", iso3: "SYR", numeric: "760", address: {} },
  { name: "Taiwan (Province of China)", iso2: "TW", iso3: "TWN", numeric: "158", address: {} },
  { name: "Tajikistan", iso2: "TJ", iso3: "TJK", numeric: "762", address: {} },
  { name: "Tanzania, United Republic of", iso2: "TZ", iso3: "TZA", numeric: "834", address: {} },
  { name: "Thailand", iso2: "TH", iso3: "THA", numeric: "764", address: {} },
  { name: "Timor-Leste", iso2: "TL", iso3: "TLS", numeric: "626", address: {} },
  { name: "Togo", iso2: "TG", iso3: "TGO", numeric: "768", address: {} },
  { name: "Tokelau", iso2: "TK", iso3: "TKL", numeric: "772", address: {} },
  { name: "Tonga", iso2: "TO", iso3: "TON", numeric: "776", address: {} },
  { name: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", numeric: "780", address: {} },
  { name: "Tunisia", iso2: "TN", iso3: "TUN", numeric: "788", address: {} },
  { name: "Turkey", iso2: "TR", iso3: "TUR", numeric: "792", address: {} },
  { name: "Turkmenistan", iso2: "TM", iso3: "TKM", numeric: "795", address: {} },
  { name: "Turks and Caicos Islands (the)", iso2: "TC", iso3: "TCA", numeric: "796", address: {} },
  { name: "Tuvalu", iso2: "TV", iso3: "TUV", numeric: "798", address: {} },
  { name: "Uganda", iso2: "UG", iso3: "UGA", numeric: "800", address: {} },
  { name: "Ukraine", iso2: "UA", iso3: "UKR", numeric: "804", address: {} },
  { name: "United Arab Emirates (the)", iso2: "AE", iso3: "ARE", numeric: "784", address: {} },
  { name: "United Kingdom of Great Britain and Northern Ireland (the)", iso2: "GB", iso3: "GBR", numeric: "826", address: {} },
  { name: "United States Minor Outlying Islands (the)", iso2: "UM", iso3: "UMI", numeric: "581", address: {} },
  { name: "United States of America (the)", iso2: "US", iso3: "USA", numeric: "840", address: Addresses_US },
  { name: "Uruguay", iso2: "UY", iso3: "URY", numeric: "858", address: {} },
  { name: "Uzbekistan", iso2: "UZ", iso3: "UZB", numeric: "860", address: {} },
  { name: "Vanuatu", iso2: "VU", iso3: "VUT", numeric: "548", address: {} },
  { name: "Venezuela (Bolivarian Republic of)", iso2: "VE", iso3: "VEN", numeric: "862", address: {} },
  { name: "Viet Nam", iso2: "VN", iso3: "VNM", numeric: "704", address: Addresses_Vietnam },
  { name: "Virgin Islands (British)", iso2: "VG", iso3: "VGB", numeric: "092", address: {} },
  { name: "Virgin Islands (U.S.)", iso2: "VI", iso3: "VIR", numeric: "850", address: {} },
  { name: "Wallis and Futuna", iso2: "WF", iso3: "WLF", numeric: "876", address: {} },
  { name: "Western Sahara", iso2: "EH", iso3: "ESH", numeric: "732", address: {} },
  { name: "Yemen", iso2: "YE", iso3: "YEM", numeric: "887", address: {} },
  { name: "Zambia", iso2: "ZM", iso3: "ZMB", numeric: "894", address: {} },
  { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE", numeric: "716", address: {} },
  { name: "Åland Islands", iso2: "AX", iso3: "ALA", numeric: "248", address: {} },
]

Countries.where = ({name = [], iso2 = [], iso3 = [], numeric = []}) => {
  let result
  if (name.length > 0) { result = Countries.filter((country) => name.includes(country.name)) }
  if (iso2.length > 0) { result = Countries.filter((country) => iso2.includes(country.iso2)) }
  if (iso3.length > 0) { result = Countries.filter((country) => iso3.includes(country.iso3)) }
  if (numeric.length > 0) { result = Countries.filter((country) => numeric.includes(country.numeric)) }
  return result
}