import { Addresses_US } from "./us"
import { Addresses_Vietnam } from "./vietname"

export const Countries = [
  { name: "Afghanistan", alpha_2_code: "AF", alpha_3_code: "AFG", numeric: "004", address: {} },
  { name: "Albania", alpha_2_code: "AL", alpha_3_code: "ALB", numeric: "008", address: {} },
  { name: "Algeria", alpha_2_code: "DZ", alpha_3_code: "DZA", numeric: "012", address: {} },
  { name: "American Samoa", alpha_2_code: "AS", alpha_3_code: "ASM", numeric: "016", address: {} },
  { name: "Andorra", alpha_2_code: "AD", alpha_3_code: "AND", numeric: "020", address: {} },
  { name: "Angola", alpha_2_code: "AO", alpha_3_code: "AGO", numeric: "024", address: {} },
  { name: "Anguilla", alpha_2_code: "AI", alpha_3_code: "AIA", numeric: "660", address: {} },
  { name: "Antarctica", alpha_2_code: "AQ", alpha_3_code: "ATA", numeric: "010", address: {} },
  { name: "Antigua and Barbuda", alpha_2_code: "AG", alpha_3_code: "ATG", numeric: "028", address: {} },
  { name: "Argentina", alpha_2_code: "AR", alpha_3_code: "ARG", numeric: "032", address: {} },
  { name: "Armenia", alpha_2_code: "AM", alpha_3_code: "ARM", numeric: "051", address: {} },
  { name: "Aruba", alpha_2_code: "AW", alpha_3_code: "ABW", numeric: "533", address: {} },
  { name: "Australia", alpha_2_code: "AU", alpha_3_code: "AUS", numeric: "036", address: {} },
  { name: "Austria", alpha_2_code: "AT", alpha_3_code: "AUT", numeric: "040", address: {} },
  { name: "Azerbaijan", alpha_2_code: "AZ", alpha_3_code: "AZE", numeric: "031", address: {} },
  { name: "Bahamas (the)", alpha_2_code: "BS", alpha_3_code: "BHS", numeric: "044", address: {} },
  { name: "Bahrain", alpha_2_code: "BH", alpha_3_code: "BHR", numeric: "048", address: {} },
  { name: "Bangladesh", alpha_2_code: "BD", alpha_3_code: "BGD", numeric: "050", address: {} },
  { name: "Barbados", alpha_2_code: "BB", alpha_3_code: "BRB", numeric: "052", address: {} },
  { name: "Belarus", alpha_2_code: "BY", alpha_3_code: "BLR", numeric: "112", address: {} },
  { name: "Belgium", alpha_2_code: "BE", alpha_3_code: "BEL", numeric: "056", address: {} },
  { name: "Belize", alpha_2_code: "BZ", alpha_3_code: "BLZ", numeric: "084", address: {} },
  { name: "Benin", alpha_2_code: "BJ", alpha_3_code: "BEN", numeric: "204", address: {} },
  { name: "Bermuda", alpha_2_code: "BM", alpha_3_code: "BMU", numeric: "060", address: {} },
  { name: "Bhutan", alpha_2_code: "BT", alpha_3_code: "BTN", numeric: "064", address: {} },
  { name: "Bolivia (Plurinational State of)", alpha_2_code: "BO", alpha_3_code: "BOL", numeric: "068", address: {} },
  { name: "Bonaire, Sint Eustatius and Saba", alpha_2_code: "BQ", alpha_3_code: "BES", numeric: "535", address: {} },
  { name: "Bosnia and Herzegovina", alpha_2_code: "BA", alpha_3_code: "BIH", numeric: "070", address: {} },
  { name: "Botswana", alpha_2_code: "BW", alpha_3_code: "BWA", numeric: "072", address: {} },
  { name: "Bouvet Island", alpha_2_code: "BV", alpha_3_code: "BVT", numeric: "074", address: {} },
  { name: "Brazil", alpha_2_code: "BR", alpha_3_code: "BRA", numeric: "076", address: {} },
  { name: "British Indian Ocean Territory (the)", alpha_2_code: "IO", alpha_3_code: "IOT", numeric: "086", address: {} },
  { name: "Brunei Darussalam", alpha_2_code: "BN", alpha_3_code: "BRN", numeric: "096", address: {} },
  { name: "Bulgaria", alpha_2_code: "BG", alpha_3_code: "BGR", numeric: "100", address: {} },
  { name: "Burkina Faso", alpha_2_code: "BF", alpha_3_code: "BFA", numeric: "854", address: {} },
  { name: "Burundi", alpha_2_code: "BI", alpha_3_code: "BDI", numeric: "108", address: {} },
  { name: "Cabo Verde", alpha_2_code: "CV", alpha_3_code: "CPV", numeric: "132", address: {} },
  { name: "Cambodia", alpha_2_code: "KH", alpha_3_code: "KHM", numeric: "116", address: {} },
  { name: "Cameroon", alpha_2_code: "CM", alpha_3_code: "CMR", numeric: "120", address: {} },
  { name: "Canada", alpha_2_code: "CA", alpha_3_code: "CAN", numeric: "124", address: {} },
  { name: "Cayman Islands (the)", alpha_2_code: "KY", alpha_3_code: "CYM", numeric: "136", address: {} },
  { name: "Central African Republic (the)", alpha_2_code: "CF", alpha_3_code: "CAF", numeric: "140", address: {} },
  { name: "Chad", alpha_2_code: "TD", alpha_3_code: "TCD", numeric: "148", address: {} },
  { name: "Chile", alpha_2_code: "CL", alpha_3_code: "CHL", numeric: "152", address: {} },
  { name: "China", alpha_2_code: "CN", alpha_3_code: "CHN", numeric: "156", address: {} },
  { name: "Christmas Island", alpha_2_code: "CX", alpha_3_code: "CXR", numeric: "162", address: {} },
  { name: "Cocos (Keeling) Islands (the)", alpha_2_code: "CC", alpha_3_code: "CCK", numeric: "166", address: {} },
  { name: "Colombia", alpha_2_code: "CO", alpha_3_code: "COL", numeric: "170", address: {} },
  { name: "Comoros (the)", alpha_2_code: "KM", alpha_3_code: "COM", numeric: "174", address: {} },
  { name: "Congo (the Democratic Republic of the)", alpha_2_code: "CD", alpha_3_code: "COD", numeric: "180", address: {} },
  { name: "Congo (the)", alpha_2_code: "CG", alpha_3_code: "COG", numeric: "178", address: {} },
  { name: "Cook Islands (the)", alpha_2_code: "CK", alpha_3_code: "COK", numeric: "184", address: {} },
  { name: "Costa Rica", alpha_2_code: "CR", alpha_3_code: "CRI", numeric: "188", address: {} },
  { name: "Croatia", alpha_2_code: "HR", alpha_3_code: "HRV", numeric: "191", address: {} },
  { name: "Cuba", alpha_2_code: "CU", alpha_3_code: "CUB", numeric: "192", address: {} },
  { name: "Curaçao", alpha_2_code: "CW", alpha_3_code: "CUW", numeric: "531", address: {} },
  { name: "Cyprus", alpha_2_code: "CY", alpha_3_code: "CYP", numeric: "196", address: {} },
  { name: "Czechia", alpha_2_code: "CZ", alpha_3_code: "CZE", numeric: "203", address: {} },
  { name: "Côte d'Ivoire", alpha_2_code: "CI", alpha_3_code: "CIV", numeric: "384", address: {} },
  { name: "Denmark", alpha_2_code: "DK", alpha_3_code: "DNK", numeric: "208", address: {} },
  { name: "Djibouti", alpha_2_code: "DJ", alpha_3_code: "DJI", numeric: "262", address: {} },
  { name: "Dominica", alpha_2_code: "DM", alpha_3_code: "DMA", numeric: "212", address: {} },
  { name: "Dominican Republic (the)", alpha_2_code: "DO", alpha_3_code: "DOM", numeric: "214", address: {} },
  { name: "Ecuador", alpha_2_code: "EC", alpha_3_code: "ECU", numeric: "218", address: {} },
  { name: "Egypt", alpha_2_code: "EG", alpha_3_code: "EGY", numeric: "818", address: {} },
  { name: "El Salvador", alpha_2_code: "SV", alpha_3_code: "SLV", numeric: "222", address: {} },
  { name: "Equatorial Guinea", alpha_2_code: "GQ", alpha_3_code: "GNQ", numeric: "226", address: {} },
  { name: "Eritrea", alpha_2_code: "ER", alpha_3_code: "ERI", numeric: "232", address: {} },
  { name: "Estonia", alpha_2_code: "EE", alpha_3_code: "EST", numeric: "233", address: {} },
  { name: "Eswatini", alpha_2_code: "SZ", alpha_3_code: "SWZ", numeric: "748", address: {} },
  { name: "Ethiopia", alpha_2_code: "ET", alpha_3_code: "ETH", numeric: "231", address: {} },
  { name: "Falkland Islands (the) [Malvinas]", alpha_2_code: "FK", alpha_3_code: "FLK", numeric: "238", address: {} },
  { name: "Faroe Islands (the)", alpha_2_code: "FO", alpha_3_code: "FRO", numeric: "234", address: {} },
  { name: "Fiji", alpha_2_code: "FJ", alpha_3_code: "FJI", numeric: "242", address: {} },
  { name: "Finland", alpha_2_code: "FI", alpha_3_code: "FIN", numeric: "246", address: {} },
  { name: "France", alpha_2_code: "FR", alpha_3_code: "FRA", numeric: "250", address: {} },
  { name: "French Guiana", alpha_2_code: "GF", alpha_3_code: "GUF", numeric: "254", address: {} },
  { name: "French Polynesia", alpha_2_code: "PF", alpha_3_code: "PYF", numeric: "258", address: {} },
  { name: "French Southern Territories (the)", alpha_2_code: "TF", alpha_3_code: "ATF", numeric: "260", address: {} },
  { name: "Gabon", alpha_2_code: "GA", alpha_3_code: "GAB", numeric: "266", address: {} },
  { name: "Gambia (the)", alpha_2_code: "GM", alpha_3_code: "GMB", numeric: "270", address: {} },
  { name: "Georgia", alpha_2_code: "GE", alpha_3_code: "GEO", numeric: "268", address: {} },
  { name: "Germany", alpha_2_code: "DE", alpha_3_code: "DEU", numeric: "276", address: {} },
  { name: "Ghana", alpha_2_code: "GH", alpha_3_code: "GHA", numeric: "288", address: {} },
  { name: "Gibraltar", alpha_2_code: "GI", alpha_3_code: "GIB", numeric: "292", address: {} },
  { name: "Greece", alpha_2_code: "GR", alpha_3_code: "GRC", numeric: "300", address: {} },
  { name: "Greenland", alpha_2_code: "GL", alpha_3_code: "GRL", numeric: "304", address: {} },
  { name: "Grenada", alpha_2_code: "GD", alpha_3_code: "GRD", numeric: "308", address: {} },
  { name: "Guadeloupe", alpha_2_code: "GP", alpha_3_code: "GLP", numeric: "312", address: {} },
  { name: "Guam", alpha_2_code: "GU", alpha_3_code: "GUM", numeric: "316", address: {} },
  { name: "Guatemala", alpha_2_code: "GT", alpha_3_code: "GTM", numeric: "320", address: {} },
  { name: "Guernsey", alpha_2_code: "GG", alpha_3_code: "GGY", numeric: "831", address: {} },
  { name: "Guinea", alpha_2_code: "GN", alpha_3_code: "GIN", numeric: "324", address: {} },
  { name: "Guinea-Bissau", alpha_2_code: "GW", alpha_3_code: "GNB", numeric: "624", address: {} },
  { name: "Guyana", alpha_2_code: "GY", alpha_3_code: "GUY", numeric: "328", address: {} },
  { name: "Haiti", alpha_2_code: "HT", alpha_3_code: "HTI", numeric: "332", address: {} },
  { name: "Heard Island and McDonald Islands", alpha_2_code: "HM", alpha_3_code: "HMD", numeric: "334", address: {} },
  { name: "Holy See (the)", alpha_2_code: "VA", alpha_3_code: "VAT", numeric: "336", address: {} },
  { name: "Honduras", alpha_2_code: "HN", alpha_3_code: "HND", numeric: "340", address: {} },
  { name: "Hong Kong", alpha_2_code: "HK", alpha_3_code: "HKG", numeric: "344", address: {} },
  { name: "Hungary", alpha_2_code: "HU", alpha_3_code: "HUN", numeric: "348", address: {} },
  { name: "Iceland", alpha_2_code: "IS", alpha_3_code: "ISL", numeric: "352", address: {} },
  { name: "India", alpha_2_code: "IN", alpha_3_code: "IND", numeric: "356", address: {} },
  { name: "Indonesia", alpha_2_code: "ID", alpha_3_code: "IDN", numeric: "360", address: {} },
  { name: "Iran (Islamic Republic of)", alpha_2_code: "IR", alpha_3_code: "IRN", numeric: "364", address: {} },
  { name: "Iraq", alpha_2_code: "IQ", alpha_3_code: "IRQ", numeric: "368", address: {} },
  { name: "Ireland", alpha_2_code: "IE", alpha_3_code: "IRL", numeric: "372", address: {} },
  { name: "Isle of Man", alpha_2_code: "IM", alpha_3_code: "IMN", numeric: "833", address: {} },
  { name: "Israel", alpha_2_code: "IL", alpha_3_code: "ISR", numeric: "376", address: {} },
  { name: "Italy", alpha_2_code: "IT", alpha_3_code: "ITA", numeric: "380", address: {} },
  { name: "Jamaica", alpha_2_code: "JM", alpha_3_code: "JAM", numeric: "388", address: {} },
  { name: "Japan", alpha_2_code: "JP", alpha_3_code: "JPN", numeric: "392", address: {} },
  { name: "Jersey", alpha_2_code: "JE", alpha_3_code: "JEY", numeric: "832", address: {} },
  { name: "Jordan", alpha_2_code: "JO", alpha_3_code: "JOR", numeric: "400", address: {} },
  { name: "Kazakhstan", alpha_2_code: "KZ", alpha_3_code: "KAZ", numeric: "398", address: {} },
  { name: "Kenya", alpha_2_code: "KE", alpha_3_code: "KEN", numeric: "404", address: {} },
  { name: "Kiribati", alpha_2_code: "KI", alpha_3_code: "KIR", numeric: "296", address: {} },
  { name: "Korea (the Democratic People's Republic of)", alpha_2_code: "KP", alpha_3_code: "PRK", numeric: "408", address: {} },
  { name: "Korea (the Republic of)", alpha_2_code: "KR", alpha_3_code: "KOR", numeric: "410", address: {} },
  { name: "Kuwait", alpha_2_code: "KW", alpha_3_code: "KWT", numeric: "414", address: {} },
  { name: "Kyrgyzstan", alpha_2_code: "KG", alpha_3_code: "KGZ", numeric: "417", address: {} },
  { name: "Lao People's Democratic Republic (the)", alpha_2_code: "LA", alpha_3_code: "LAO", numeric: "418", address: {} },
  { name: "Latvia", alpha_2_code: "LV", alpha_3_code: "LVA", numeric: "428", address: {} },
  { name: "Lebanon", alpha_2_code: "LB", alpha_3_code: "LBN", numeric: "422", address: {} },
  { name: "Lesotho", alpha_2_code: "LS", alpha_3_code: "LSO", numeric: "426", address: {} },
  { name: "Liberia", alpha_2_code: "LR", alpha_3_code: "LBR", numeric: "430", address: {} },
  { name: "Libya", alpha_2_code: "LY", alpha_3_code: "LBY", numeric: "434", address: {} },
  { name: "Liechtenstein", alpha_2_code: "LI", alpha_3_code: "LIE", numeric: "438", address: {} },
  { name: "Lithuania", alpha_2_code: "LT", alpha_3_code: "LTU", numeric: "440", address: {} },
  { name: "Luxembourg", alpha_2_code: "LU", alpha_3_code: "LUX", numeric: "442", address: {} },
  { name: "Macao", alpha_2_code: "MO", alpha_3_code: "MAC", numeric: "446", address: {} },
  { name: "Madagascar", alpha_2_code: "MG", alpha_3_code: "MDG", numeric: "450", address: {} },
  { name: "Malawi", alpha_2_code: "MW", alpha_3_code: "MWI", numeric: "454", address: {} },
  { name: "Malaysia", alpha_2_code: "MY", alpha_3_code: "MYS", numeric: "458", address: {} },
  { name: "Maldives", alpha_2_code: "MV", alpha_3_code: "MDV", numeric: "462", address: {} },
  { name: "Mali", alpha_2_code: "ML", alpha_3_code: "MLI", numeric: "466", address: {} },
  { name: "Malta", alpha_2_code: "MT", alpha_3_code: "MLT", numeric: "470", address: {} },
  { name: "Marshall Islands (the)", alpha_2_code: "MH", alpha_3_code: "MHL", numeric: "584", address: {} },
  { name: "Martinique", alpha_2_code: "MQ", alpha_3_code: "MTQ", numeric: "474", address: {} },
  { name: "Mauritania", alpha_2_code: "MR", alpha_3_code: "MRT", numeric: "478", address: {} },
  { name: "Mauritius", alpha_2_code: "MU", alpha_3_code: "MUS", numeric: "480", address: {} },
  { name: "Mayotte", alpha_2_code: "YT", alpha_3_code: "MYT", numeric: "175", address: {} },
  { name: "Mexico", alpha_2_code: "MX", alpha_3_code: "MEX", numeric: "484", address: {} },
  { name: "Micronesia (Federated States of)", alpha_2_code: "FM", alpha_3_code: "FSM", numeric: "583", address: {} },
  { name: "Moldova (the Republic of)", alpha_2_code: "MD", alpha_3_code: "MDA", numeric: "498", address: {} },
  { name: "Monaco", alpha_2_code: "MC", alpha_3_code: "MCO", numeric: "492", address: {} },
  { name: "Mongolia", alpha_2_code: "MN", alpha_3_code: "MNG", numeric: "496", address: {} },
  { name: "Montenegro", alpha_2_code: "ME", alpha_3_code: "MNE", numeric: "499", address: {} },
  { name: "Montserrat", alpha_2_code: "MS", alpha_3_code: "MSR", numeric: "500", address: {} },
  { name: "Morocco", alpha_2_code: "MA", alpha_3_code: "MAR", numeric: "504", address: {} },
  { name: "Mozambique", alpha_2_code: "MZ", alpha_3_code: "MOZ", numeric: "508", address: {} },
  { name: "Myanmar", alpha_2_code: "MM", alpha_3_code: "MMR", numeric: "104", address: {} },
  { name: "Namibia", alpha_2_code: "NA", alpha_3_code: "NAM", numeric: "516", address: {} },
  { name: "Nauru", alpha_2_code: "NR", alpha_3_code: "NRU", numeric: "520", address: {} },
  { name: "Nepal", alpha_2_code: "NP", alpha_3_code: "NPL", numeric: "524", address: {} },
  { name: "Netherlands (the)", alpha_2_code: "NL", alpha_3_code: "NLD", numeric: "528", address: {} },
  { name: "New Caledonia", alpha_2_code: "NC", alpha_3_code: "NCL", numeric: "540", address: {} },
  { name: "New Zealand", alpha_2_code: "NZ", alpha_3_code: "NZL", numeric: "554", address: {} },
  { name: "Nicaragua", alpha_2_code: "NI", alpha_3_code: "NIC", numeric: "558", address: {} },
  { name: "Niger (the)", alpha_2_code: "NE", alpha_3_code: "NER", numeric: "562", address: {} },
  { name: "Nigeria", alpha_2_code: "NG", alpha_3_code: "NGA", numeric: "566", address: {} },
  { name: "Niue", alpha_2_code: "NU", alpha_3_code: "NIU", numeric: "570", address: {} },
  { name: "Norfolk Island", alpha_2_code: "NF", alpha_3_code: "NFK", numeric: "574", address: {} },
  { name: "Northern Mariana Islands (the)", alpha_2_code: "MP", alpha_3_code: "MNP", numeric: "580", address: {} },
  { name: "Norway", alpha_2_code: "NO", alpha_3_code: "NOR", numeric: "578", address: {} },
  { name: "Oman", alpha_2_code: "OM", alpha_3_code: "OMN", numeric: "512", address: {} },
  { name: "Pakistan", alpha_2_code: "PK", alpha_3_code: "PAK", numeric: "586", address: {} },
  { name: "Palau", alpha_2_code: "PW", alpha_3_code: "PLW", numeric: "585", address: {} },
  { name: "Palestine, State of", alpha_2_code: "PS", alpha_3_code: "PSE", numeric: "275", address: {} },
  { name: "Panama", alpha_2_code: "PA", alpha_3_code: "PAN", numeric: "591", address: {} },
  { name: "Papua New Guinea", alpha_2_code: "PG", alpha_3_code: "PNG", numeric: "598", address: {} },
  { name: "Paraguay", alpha_2_code: "PY", alpha_3_code: "PRY", numeric: "600", address: {} },
  { name: "Peru", alpha_2_code: "PE", alpha_3_code: "PER", numeric: "604", address: {} },
  { name: "Philippines (the)", alpha_2_code: "PH", alpha_3_code: "PHL", numeric: "608", address: {} },
  { name: "Pitcairn", alpha_2_code: "PN", alpha_3_code: "PCN", numeric: "612", address: {} },
  { name: "Poland", alpha_2_code: "PL", alpha_3_code: "POL", numeric: "616", address: {} },
  { name: "Portugal", alpha_2_code: "PT", alpha_3_code: "PRT", numeric: "620", address: {} },
  { name: "Puerto Rico", alpha_2_code: "PR", alpha_3_code: "PRI", numeric: "630", address: {} },
  { name: "Qatar", alpha_2_code: "QA", alpha_3_code: "QAT", numeric: "634", address: {} },
  { name: "Republic of North Macedonia", alpha_2_code: "MK", alpha_3_code: "MKD", numeric: "807", address: {} },
  { name: "Romania", alpha_2_code: "RO", alpha_3_code: "ROU", numeric: "642", address: {} },
  { name: "Russian Federation (the)", alpha_2_code: "RU", alpha_3_code: "RUS", numeric: "643", address: {} },
  { name: "Rwanda", alpha_2_code: "RW", alpha_3_code: "RWA", numeric: "646", address: {} },
  { name: "Réunion", alpha_2_code: "RE", alpha_3_code: "REU", numeric: "638", address: {} },
  { name: "Saint Barthélemy", alpha_2_code: "BL", alpha_3_code: "BLM", numeric: "652", address: {} },
  { name: "Saint Helena, Ascension and Tristan da Cunha", alpha_2_code: "SH", alpha_3_code: "SHN", numeric: "654", address: {} },
  { name: "Saint Kitts and Nevis", alpha_2_code: "KN", alpha_3_code: "KNA", numeric: "659", address: {} },
  { name: "Saint Lucia", alpha_2_code: "LC", alpha_3_code: "LCA", numeric: "662", address: {} },
  { name: "Saint Martin (French part)", alpha_2_code: "MF", alpha_3_code: "MAF", numeric: "663", address: {} },
  { name: "Saint Pierre and Miquelon", alpha_2_code: "PM", alpha_3_code: "SPM", numeric: "666", address: {} },
  { name: "Saint Vincent and the Grenadines", alpha_2_code: "VC", alpha_3_code: "VCT", numeric: "670", address: {} },
  { name: "Samoa", alpha_2_code: "WS", alpha_3_code: "WSM", numeric: "882", address: {} },
  { name: "San Marino", alpha_2_code: "SM", alpha_3_code: "SMR", numeric: "674", address: {} },
  { name: "Sao Tome and Principe", alpha_2_code: "ST", alpha_3_code: "STP", numeric: "678", address: {} },
  { name: "Saudi Arabia", alpha_2_code: "SA", alpha_3_code: "SAU", numeric: "682", address: {} },
  { name: "Senegal", alpha_2_code: "SN", alpha_3_code: "SEN", numeric: "686", address: {} },
  { name: "Serbia", alpha_2_code: "RS", alpha_3_code: "SRB", numeric: "688", address: {} },
  { name: "Seychelles", alpha_2_code: "SC", alpha_3_code: "SYC", numeric: "690", address: {} },
  { name: "Sierra Leone", alpha_2_code: "SL", alpha_3_code: "SLE", numeric: "694", address: {} },
  { name: "Singapore", alpha_2_code: "SG", alpha_3_code: "SGP", numeric: "702", address: {} },
  { name: "Sint Maarten (Dutch part)", alpha_2_code: "SX", alpha_3_code: "SXM", numeric: "534", address: {} },
  { name: "Slovakia", alpha_2_code: "SK", alpha_3_code: "SVK", numeric: "703", address: {} },
  { name: "Slovenia", alpha_2_code: "SI", alpha_3_code: "SVN", numeric: "705", address: {} },
  { name: "Solomon Islands", alpha_2_code: "SB", alpha_3_code: "SLB", numeric: "090", address: {} },
  { name: "Somalia", alpha_2_code: "SO", alpha_3_code: "SOM", numeric: "706", address: {} },
  { name: "South Africa", alpha_2_code: "ZA", alpha_3_code: "ZAF", numeric: "710", address: {} },
  { name: "South Georgia and the South Sandwich Islands", alpha_2_code: "GS", alpha_3_code: "SGS", numeric: "239", address: {} },
  { name: "South Sudan", alpha_2_code: "SS", alpha_3_code: "SSD", numeric: "728", address: {} },
  { name: "Spain", alpha_2_code: "ES", alpha_3_code: "ESP", numeric: "724", address: {} },
  { name: "Sri Lanka", alpha_2_code: "LK", alpha_3_code: "LKA", numeric: "144", address: {} },
  { name: "Sudan (the)", alpha_2_code: "SD", alpha_3_code: "SDN", numeric: "729", address: {} },
  { name: "Suriname", alpha_2_code: "SR", alpha_3_code: "SUR", numeric: "740", address: {} },
  { name: "Svalbard and Jan Mayen", alpha_2_code: "SJ", alpha_3_code: "SJM", numeric: "744", address: {} },
  { name: "Sweden", alpha_2_code: "SE", alpha_3_code: "SWE", numeric: "752", address: {} },
  { name: "Switzerland", alpha_2_code: "CH", alpha_3_code: "CHE", numeric: "756", address: {} },
  { name: "Syrian Arab Republic", alpha_2_code: "SY", alpha_3_code: "SYR", numeric: "760", address: {} },
  { name: "Taiwan (Province of China)", alpha_2_code: "TW", alpha_3_code: "TWN", numeric: "158", address: {} },
  { name: "Tajikistan", alpha_2_code: "TJ", alpha_3_code: "TJK", numeric: "762", address: {} },
  { name: "Tanzania, United Republic of", alpha_2_code: "TZ", alpha_3_code: "TZA", numeric: "834", address: {} },
  { name: "Thailand", alpha_2_code: "TH", alpha_3_code: "THA", numeric: "764", address: {} },
  { name: "Timor-Leste", alpha_2_code: "TL", alpha_3_code: "TLS", numeric: "626", address: {} },
  { name: "Togo", alpha_2_code: "TG", alpha_3_code: "TGO", numeric: "768", address: {} },
  { name: "Tokelau", alpha_2_code: "TK", alpha_3_code: "TKL", numeric: "772", address: {} },
  { name: "Tonga", alpha_2_code: "TO", alpha_3_code: "TON", numeric: "776", address: {} },
  { name: "Trinidad and Tobago", alpha_2_code: "TT", alpha_3_code: "TTO", numeric: "780", address: {} },
  { name: "Tunisia", alpha_2_code: "TN", alpha_3_code: "TUN", numeric: "788", address: {} },
  { name: "Turkey", alpha_2_code: "TR", alpha_3_code: "TUR", numeric: "792", address: {} },
  { name: "Turkmenistan", alpha_2_code: "TM", alpha_3_code: "TKM", numeric: "795", address: {} },
  { name: "Turks and Caicos Islands (the)", alpha_2_code: "TC", alpha_3_code: "TCA", numeric: "796", address: {} },
  { name: "Tuvalu", alpha_2_code: "TV", alpha_3_code: "TUV", numeric: "798", address: {} },
  { name: "Uganda", alpha_2_code: "UG", alpha_3_code: "UGA", numeric: "800", address: {} },
  { name: "Ukraine", alpha_2_code: "UA", alpha_3_code: "UKR", numeric: "804", address: {} },
  { name: "United Arab Emirates (the)", alpha_2_code: "AE", alpha_3_code: "ARE", numeric: "784", address: {} },
  { name: "United Kingdom of Great Britain and Northern Ireland (the)", alpha_2_code: "GB", alpha_3_code: "GBR", numeric: "826", address: {} },
  { name: "United States Minor Outlying Islands (the)", alpha_2_code: "UM", alpha_3_code: "UMI", numeric: "581", address: {} },
  { name: "United States of America (the)", alpha_2_code: "US", alpha_3_code: "USA", numeric: "840", address: Addresses_US },
  { name: "Uruguay", alpha_2_code: "UY", alpha_3_code: "URY", numeric: "858", address: {} },
  { name: "Uzbekistan", alpha_2_code: "UZ", alpha_3_code: "UZB", numeric: "860", address: {} },
  { name: "Vanuatu", alpha_2_code: "VU", alpha_3_code: "VUT", numeric: "548", address: {} },
  { name: "Venezuela (Bolivarian Republic of)", alpha_2_code: "VE", alpha_3_code: "VEN", numeric: "862", address: {} },
  { name: "Viet Nam", alpha_2_code: "VN", alpha_3_code: "VNM", numeric: "704", address: Addresses_Vietnam },
  { name: "Virgin Islands (British)", alpha_2_code: "VG", alpha_3_code: "VGB", numeric: "092", address: {} },
  { name: "Virgin Islands (U.S.)", alpha_2_code: "VI", alpha_3_code: "VIR", numeric: "850", address: {} },
  { name: "Wallis and Futuna", alpha_2_code: "WF", alpha_3_code: "WLF", numeric: "876", address: {} },
  { name: "Western Sahara", alpha_2_code: "EH", alpha_3_code: "ESH", numeric: "732", address: {} },
  { name: "Yemen", alpha_2_code: "YE", alpha_3_code: "YEM", numeric: "887", address: {} },
  { name: "Zambia", alpha_2_code: "ZM", alpha_3_code: "ZMB", numeric: "894", address: {} },
  { name: "Zimbabwe", alpha_2_code: "ZW", alpha_3_code: "ZWE", numeric: "716", address: {} },
  { name: "Åland Islands", alpha_2_code: "AX", alpha_3_code: "ALA", numeric: "248", address: {} },
]

Countries.where = ({name = [], alpha_2_code = [], alpha_3_code = [], numeric = []}) => {
  let result
  if (name.length > 0) { result = Countries.filter((country) => name.includes(country.name)) }
  if (alpha_2_code.length > 0) { result = Countries.filter((country) => alpha_2_code.includes(country.alpha_2_code)) }
  if (alpha_3_code.length > 0) { result = Countries.filter((country) => alpha_3_code.includes(country.alpha_3_code)) }
  if (numeric.length > 0) { result = Countries.filter((country) => numeric.includes(country.numeric)) }
  return result
}