export const Addresses_Vietnam = [
  { province: "An Giang" },
  { province: "Bà Rịa – Vũng Tàu" },
  { province: "Bắc Giang" },
  { province: "Bắc Kạn" },
  { province: "Bạc Liêu" },
  { province: "Bắc Ninh" },
  { province: "Bến Tre" },
  { province: "Bình Định" },
  { province: "Bình Dương" },
  { province: "Bình Phước" },
  { province: "Bình Thuận" },
  { province: "Cà Mau" },
  { province: "Cần Thơ" },
  { province: "Cao Bằng" },
  { province: "Đà Nẵng" },
  { province: "Đắk Lắk" },
  { province: "Đắk Nông" },
  { province: "Điện Biên" },
  { province: "Đồng Nai" },
  { province: "Đồng Tháp" },
  { province: "Gia Lai" },
  { province: "Hà Giang" },
  { province: "Hà Nam" },
  { province: "Hà Nội" },
  { province: "Hà Tĩnh" },
  { province: "Hải Dương" },
  { province: "Hải Phòng" },
  { province: "Hậu Giang" },
  { province: "Hòa Bình" },
  { province: "Hưng Yên" },
  { province: "Khánh Hòa" },
  { province: "Kiên Giang" },
  { province: "Kon Tum" },
  { province: "Lai Châu" },
  { province: "Lâm Đồng" },
  { province: "Lạng Sơn" },
  { province: "Lào Cai" },
  { province: "Long An" },
  { province: "Nam Định" },
  { province: "Nghệ An" },
  { province: "Ninh Bình" },
  { province: "Ninh Thuận" },
  { province: "Phú Thọ" },
  { province: "Phú Yên" },
  { province: "Quảng Bình" },
  { province: "Quảng Nam" },
  { province: "Quảng Ngãi" },
  { province: "Quảng Ninh" },
  { province: "Quảng Trị" },
  { province: "Sóc Trăng" },
  { province: "Sơn La" },
  { province: "Tây Ninh" },
  { province: "Thái Bình" },
  { province: "Thái Nguyên" },
  { province: "Thanh Hóa" },
  { province: "Thành phố Hồ Chí Minh", ditrict: {
    "Quận 1": {},
    "Quận 2": {},
    "Quận 3": {},
    "Quận 4": {},
    "Quận 5": {},
    "Quận 6": {},
    "Quận 7": {},
    "Quận 8": {},
    "Quận 9": {},
    "Quận 10": {},
    "Quận 11": {},
    "Quận 12": {},
    "Quận Bình Thạnh": {},
    "Quận Gò Vấp": {},
    "Quận Phú Nhuận": {},
    "Quận Tân Bình": {},
    "Quận Tân Phú": {},
    "Quận Bình Tân": {},
    "Thành phố Thủ Đức": {},
    "Huyện Nhà Bè": {},
    "Huyện Hóc Môn": {},
    "Huyện Bình Chánh": {},
    "Huyện Củ Chi": {},
    "Huyện Cần Giờ": {},
  } },
  { province: "Thừa Thiên Huế" },
  { province: "Tiền Giang" },
  { province: "Trà Vinh" },
  { province: "Tuyên Quang" },
  { province: "Vĩnh Long" },
  { province: "Vĩnh Phúc" },
  { province: "Yên Bái" },
]

Addresses_Vietnam.address_format = ['country', "province", "district", "ward"]