# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Carousel::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Carousel::DefaultComponent`.

class Carousel::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
