# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Table::DemoComponent`.
# Please instead update this file by running `bin/tapioca dsl Table::DemoComponent`.

class Table::DemoComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
