# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Footer::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Footer::DefaultComponent`.

class Footer::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
