# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Footer::NormalComponent`.
# Please instead update this file by running `bin/tapioca dsl Footer::NormalComponent`.

class Footer::NormalComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
