# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Page::Demo::FooterComponent`.
# Please instead update this file by running `bin/tapioca dsl Page::Demo::FooterComponent`.

class Page::Demo::FooterComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
