# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Page::Demo::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Page::Demo::HeaderComponent`.

class Page::Demo::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
