# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Editor::EditorjsComponent`.
# Please instead update this file by running `bin/tapioca dsl Editor::EditorjsComponent`.

class Editor::EditorjsComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
