# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Editor::TrixComponent`.
# Please instead update this file by running `bin/tapioca dsl Editor::TrixComponent`.

class Editor::TrixComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
