# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hr::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Hr::DefaultComponent`.

class Hr::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
