# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hr::TextComponent`.
# Please instead update this file by running `bin/tapioca dsl Hr::TextComponent`.

class Hr::TextComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
