# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Tab::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Tab::DefaultComponent`.

class Tab::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
