# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Navbar::FloatComponent`.
# Please instead update this file by running `bin/tapioca dsl Navbar::FloatComponent`.

class Navbar::FloatComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
