# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Accordion::BlockComponent`.
# Please instead update this file by running `bin/tapioca dsl Accordion::BlockComponent`.

class Accordion::BlockComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
