# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Accordion::GroupComponent`.
# Please instead update this file by running `bin/tapioca dsl Accordion::GroupComponent`.

class Accordion::GroupComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
