# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Accordion::HeadComponent`.
# Please instead update this file by running `bin/tapioca dsl Accordion::HeadComponent`.

class Accordion::HeadComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
