# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Modal::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Modal::DefaultComponent`.

class Modal::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
