# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Calendar::TuiComponent`.
# Please instead update this file by running `bin/tapioca dsl Calendar::TuiComponent`.

class Calendar::TuiComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
