# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::AnonymousComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::AnonymousComponent`.

class Icon::AnonymousComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
