# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::Bars3Component`.
# Please instead update this file by running `bin/tapioca dsl Icon::Bars3Component`.

class Icon::Bars3Component
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
