# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::ClockComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::ClockComponent`.

class Icon::ClockComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
