# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::LinkComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::LinkComponent`.

class Icon::LinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
