# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::LongArrowComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::LongArrowComponent`.

class Icon::LongArrowComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
