# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::MoonComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::MoonComponent`.

class Icon::MoonComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
