# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::SearchComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::SearchComponent`.

class Icon::SearchComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
