# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::SmallArrowComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::SmallArrowComponent`.

class Icon::SmallArrowComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
