# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::SunComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::SunComponent`.

class Icon::SunComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
